#!/bin/sh
echo "start of postinst script"
# update needed changes in apache2
a2query -m cgi -q
ISTAT=$?
#echo "ISTAT ${ISTAT}"
set -e

if [ ${ISTAT} -ne 0 ]
then
        sudo a2enmod cgi >/dev/null 2>&1
fi

sudo service apache2 restart

systemctl daemon-reload
echo "reload"
systemctl enable can-socat-setup.service
echo "enable socat"
systemctl start can-socat-setup
echo "start socat"
systemctl enable busmaster.service
echo "enable busmaster"
systemctl start busmaster
echo "start busmaster"
systemctl enable datalogger.service
echo "enable datalogger"
systemctl start datalogger
echo "start datalogger"
echo "end of postinst script"
exit 0

