#!/bin/sh
echo "start of postinst script"
# update needed changes in apache2
a2query -m cgi -q
ISTAT=$?
#echo "ISTAT ${ISTAT}"
set -e


sudo chmod +x /etc/init.d/can-daemon
sudo update-rc.d -f can-daemon defaults
sudo service can-daemon start

sudo chown root /etc/init.d/can-daemon 
sudo chgrp root /etc/init.d/can-daemon 

if [ ${ISTAT} -ne 0 ]
then
        sudo a2enmod cgi >/dev/null 2>&1
fi

sudo service apache2 restart

systemctl daemon-reload
systemctl enable can-socat-setup.service
systemctl start can-socat-setup
systemctl enable busmaster.service
systemctl start busmaster
systemctl enable datalogger.service
systemctl start datalogger
echo "end of postinst script"
exit 0

