#!/bin/sh
echo "start of postinst script"
# update needed changes in apache2
a2query -m cgi -q
ISTAT=$?
#echo "ISTAT ${ISTAT}"
set -e

ldconfig
if [ ${ISTAT} -ne 0 ]
then
        sudo a2enmod cgi >/dev/null 2>&1
fi

mkdir -p /var/www/html/data

service apache2 restart

systemctl daemon-reload
echo "reload"

systemctl enable can-iface.service
echo "enabled caniface"
systemctl start can-iface.service
echo "started can"

systemctl enable can-socat-setup.service
echo "enabled socat"
systemctl start can-socat-setup
echo "started socat"

systemctl enable busmaster.service
echo "enabled busmaster"
systemctl start busmaster
echo "started busmaster"

systemctl enable jcodatalogger.service
echo "enabled jcodatalogger"
systemctl start jcodatalogger
echo "started jcodatalogger"

echo "end of postinst script"
exit 0

