#!/bin/sh

sudo chmod +x /etc/init.d/can-daemon
sudo update-rc.d -f can-daemon defaults
sudo service can-daemon start

sudo chown root /etc/init.d/can-daemon 
sudo chgrp root /etc/init.d/can-daemon 

sudo a2enmod cgi
sudo service apache2 reload

